trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "================================="
    echo " VARMA TECH CI/CD PIPELINE"
    echo "================================="
    echo "Validating website files..."
    test -f index.html
    test -f style.css
    test -f script.js
    echo "All website files are present."
  displayName: 'Validate Website'

- task: ArchiveFiles@2
  displayName: 'Package Website'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/varma-tech.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Website Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/varma-tech.zip'
    ArtifactName: 'varma-tech-website'
    publishLocation: 'Container'
- script: |
    git config --global user.email "azure-pipeline@users.noreply.github.com"
    git config --global user.name "Azure Pipeline"

    git clone https://x-access-token:$(GITHUB_PAT)@github.com/varma160/varma-tech.git deploy
    cd deploy

    git checkout --orphan gh-pages
    git rm -rf .

    cp ../index.html .
    cp ../style.css .
    cp ../script.js .

    git add .
    git commit -m "Deploy website from Azure DevOps"
    git push --force origin gh-pages
  displayName: 'Deploy website to GitHub Pages'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
